name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

env:
  GO_VERSION: '1.23'

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Run tests
      run: go test -v ./...

    - name: Check formatting
      run: |
        if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
          echo "The following files are not formatted:"
          gofmt -s -l .
          exit 1
        fi

    - name: Run go vet
      run: go vet ./...

    - name: Run staticcheck
      uses: dominikh/staticcheck-action@v1.3.0
      with:
        version: "2023.1.7"
        install-go: false

  build-nightly:
    name: Build Nightly (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: linux-x64
            os: ubuntu-22.04
            goos: linux
            goarch: amd64
            name: cc-switch-nightly-linux-x64
          - target: linux-arm64
            os: ubuntu-latest
            goos: linux
            goarch: arm64
            name: cc-switch-nightly-linux-arm64
          - target: windows-x64
            os: ubuntu-latest
            goos: windows
            goarch: amd64
            name: cc-switch-nightly-windows-x64
          - target: darwin-x64
            os: macos-latest
            goos: darwin
            goarch: amd64
            name: cc-switch-nightly-darwin-x64
          - target: darwin-arm64
            os: macos-latest
            goos: darwin
            goarch: arm64
            name: cc-switch-nightly-darwin-arm64

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-${{ matrix.target }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.target }}-go-

    - name: Build binary
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        CGO_ENABLED: 0
      run: |
        go build -ldflags="-s -w -X main.version=nightly-${{ github.sha }}" -o dist/cc-switch${{ matrix.goos == 'windows' && '.exe' || '' }} .

    - name: Package Linux/macOS
      if: matrix.goos != 'windows'
      run: |
        mkdir -p dist
        cd dist
        tar czf ../${{ matrix.name }}-${{ github.sha }}.tar.gz cc-switch

    - name: Package Windows
      if: matrix.goos == 'windows'
      run: |
        mkdir -p dist
        cd dist
        zip ../${{ matrix.name }}-${{ github.sha }}.zip cc-switch.exe

    - name: Upload nightly build artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.name }}-${{ github.sha }}
        path: |
          ${{ matrix.name }}-${{ github.sha }}.tar.gz
          ${{ matrix.name }}-${{ github.sha }}.zip
        retention-days: 30

  build-summary:
    name: Build Summary
    runs-on: ubuntu-latest
    needs: [test, build-nightly]
    if: always()
    steps:
    - name: Print build summary
      run: |
        echo "## 🚀 Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Commit:** \`${{ github.sha }}\`" >> $GITHUB_STEP_SUMMARY
        echo "**Branch:** \`${{ github.ref_name }}\`" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY

        if [[ "${{ needs.test.result }}" == "success" ]]; then
          echo "✅ **Tests:** Passed" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ **Tests:** Failed" >> $GITHUB_STEP_SUMMARY
        fi

        if [[ "${{ needs.build-nightly.result }}" == "success" ]]; then
          echo "✅ **Build:** All platforms built successfully" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 📦 Nightly Builds Available:" >> $GITHUB_STEP_SUMMARY
          echo "- Linux x64" >> $GITHUB_STEP_SUMMARY
          echo "- Linux ARM64" >> $GITHUB_STEP_SUMMARY
          echo "- Windows x64" >> $GITHUB_STEP_SUMMARY
          echo "- macOS x64 (Intel)" >> $GITHUB_STEP_SUMMARY
          echo "- macOS ARM64 (Apple Silicon)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "🔗 Download artifacts from the [Actions tab](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ **Build:** Some platforms failed" >> $GITHUB_STEP_SUMMARY
        fi

  nightly-release:
    name: Create Nightly Release
    runs-on: ubuntu-latest
    needs: [test, build-nightly]
    if: github.ref == 'refs/heads/main' && needs.test.result == 'success' && needs.build-nightly.result == 'success'
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: nightly-artifacts

    - name: Generate release date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Generate nightly tag
      id: tag
      run: echo "tag=nightly-${{ steps.date.outputs.date }}-${{ github.sha }}" >> $GITHUB_OUTPUT

    - name: Delete existing nightly releases
      run: |
        # Delete previous nightly releases (keep only the latest 3)
        gh release list --json tagName,isDraft | jq -r '.[] | select(.tagName | startswith("nightly-")) | select(.isDraft == false) | .tagName' | head -n 3 | while read tag; do
          echo "Deleting old nightly release: $tag"
          gh release delete "$tag" --yes || true
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create nightly release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.tag.outputs.tag }}
        name: "Nightly Build (${{ steps.date.outputs.date }})"
        body: |
          🌙 **Nightly Build** - ${{ steps.date.outputs.date }}

          **Commit:** ${{ github.sha }}
          **Branch:** ${{ github.ref_name }}
          **Build Time:** ${{ steps.date.outputs.date }}

          ## 📦 Available Downloads

          ### Linux
          - **cc-switch-nightly-linux-x64**: Standard Linux x64 build
          - **cc-switch-nightly-linux-arm64**: Linux ARM64 build

          ### macOS
          - **cc-switch-nightly-darwin-x64**: Intel Mac build
          - **cc-switch-nightly-darwin-arm64**: Apple Silicon Mac build

          ### Windows
          - **cc-switch-nightly-windows-x64**: Windows x64 build

          ## ⚠️ Important Notes

          - This is a **development build** from the latest `main` branch
          - Use at your own risk - may contain bugs or incomplete features
          - For stable releases, see the [Releases](https://github.com/${{ github.repository }}/releases) page
          - Install via NPM: `npm install -g @hobeeliu/cc-switch` (stable)

          ## 🚀 What's New

          Recent commits in this build:

          ```
          ${{ github.event.head_commit.message }}
          ```

          ---
          *Generated automatically from commit ${{ github.sha }}*
        files: nightly-artifacts/*/*
        draft: false
        prerelease: true
        make_latest: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}